// Generated by tools/audio/prepare-items.py. Frame offsets use the source rate.
export const TOOL_ATLAS = {
  "url": "/audio/item-sounds.wav",
  "sampleRate": 32000,
  "frames": 559200,
  "clips": [
    {
      "kind": "mallet-hit",
      "offsetFrames": 0,
      "lengthFrames": 8000,
      "peakSeconds": 0.01
    },
    {
      "kind": "bat-hit",
      "offsetFrames": 8000,
      "lengthFrames": 7680,
      "peakSeconds": 0.005
    },
    {
      "kind": "ball-hit",
      "offsetFrames": 15680,
      "lengthFrames": 10880,
      "peakSeconds": 0.02
    },
    {
      "kind": "pellet-hit",
      "offsetFrames": 26560,
      "lengthFrames": 2720,
      "peakSeconds": 0.005
    },
    {
      "kind": "mallet-hit",
      "offsetFrames": 29280,
      "lengthFrames": 8000,
      "peakSeconds": 0.01
    },
    {
      "kind": "bat-hit",
      "offsetFrames": 37280,
      "lengthFrames": 7680,
      "peakSeconds": 0.005
    },
    {
      "kind": "ball-hit",
      "offsetFrames": 44960,
      "lengthFrames": 10880,
      "peakSeconds": 0.02
    },
    {
      "kind": "pellet-hit",
      "offsetFrames": 55840,
      "lengthFrames": 2720,
      "peakSeconds": 0.005
    },
    {
      "kind": "mallet-hit",
      "offsetFrames": 58560,
      "lengthFrames": 8000,
      "peakSeconds": 0.01
    },
    {
      "kind": "bat-hit",
      "offsetFrames": 66560,
      "lengthFrames": 7680,
      "peakSeconds": 0.01
    },
    {
      "kind": "ball-hit",
      "offsetFrames": 74240,
      "lengthFrames": 10880,
      "peakSeconds": 0.015
    },
    {
      "kind": "pellet-hit",
      "offsetFrames": 85120,
      "lengthFrames": 2720,
      "peakSeconds": 0.005
    },
    {
      "kind": "parcel-hit",
      "offsetFrames": 87840,
      "lengthFrames": 7680,
      "peakSeconds": 0.01
    },
    {
      "kind": "parcel-hit",
      "offsetFrames": 95520,
      "lengthFrames": 7680,
      "peakSeconds": 0.01
    },
    {
      "kind": "pistol",
      "offsetFrames": 103200,
      "lengthFrames": 14720,
      "peakSeconds": 0.01
    },
    {
      "kind": "pistol",
      "offsetFrames": 117920,
      "lengthFrames": 14720,
      "peakSeconds": 0.01
    },
    {
      "kind": "pistol",
      "offsetFrames": 132640,
      "lengthFrames": 14720,
      "peakSeconds": 0.01
    },
    {
      "kind": "pistol",
      "offsetFrames": 147360,
      "lengthFrames": 14720,
      "peakSeconds": 0.01
    },
    {
      "kind": "launcher",
      "offsetFrames": 162080,
      "lengthFrames": 24960,
      "peakSeconds": 0.035
    },
    {
      "kind": "cannon",
      "offsetFrames": 187040,
      "lengthFrames": 25600,
      "peakSeconds": 0.025
    },
    {
      "kind": "launcher",
      "offsetFrames": 212640,
      "lengthFrames": 24960,
      "peakSeconds": 0.04
    },
    {
      "kind": "cannon",
      "offsetFrames": 237600,
      "lengthFrames": 25600,
      "peakSeconds": 0.025
    },
    {
      "kind": "swish",
      "offsetFrames": 263200,
      "lengthFrames": 6080,
      "peakSeconds": 0.04
    },
    {
      "kind": "heavy-swish",
      "offsetFrames": 269280,
      "lengthFrames": 8000,
      "peakSeconds": 0.065
    },
    {
      "kind": "swish",
      "offsetFrames": 277280,
      "lengthFrames": 6080,
      "peakSeconds": 0.07
    },
    {
      "kind": "heavy-swish",
      "offsetFrames": 283360,
      "lengthFrames": 8000,
      "peakSeconds": 0.1
    },
    {
      "kind": "swish",
      "offsetFrames": 291360,
      "lengthFrames": 6080,
      "peakSeconds": 0.065
    },
    {
      "kind": "heavy-swish",
      "offsetFrames": 297440,
      "lengthFrames": 8000,
      "peakSeconds": 0.1
    },
    {
      "kind": "throw",
      "offsetFrames": 305440,
      "lengthFrames": 5440,
      "peakSeconds": 0.05
    },
    {
      "kind": "throw",
      "offsetFrames": 310880,
      "lengthFrames": 5440,
      "peakSeconds": 0.055
    },
    {
      "kind": "bomb-arm",
      "offsetFrames": 316320,
      "lengthFrames": 15360,
      "peakSeconds": 0.005
    },
    {
      "kind": "bomb-arm",
      "offsetFrames": 331680,
      "lengthFrames": 15360,
      "peakSeconds": 0.005
    },
    {
      "kind": "bomb-blast",
      "offsetFrames": 347040,
      "lengthFrames": 33600,
      "peakSeconds": 0.03
    },
    {
      "kind": "bomb-blast",
      "offsetFrames": 380640,
      "lengthFrames": 33600,
      "peakSeconds": 0.03
    },
    {
      "kind": "rocket-blast",
      "offsetFrames": 414240,
      "lengthFrames": 26240,
      "peakSeconds": 0.015
    },
    {
      "kind": "rocket-blast",
      "offsetFrames": 440480,
      "lengthFrames": 26240,
      "peakSeconds": 0.015
    },
    {
      "kind": "vacuum-start",
      "offsetFrames": 466720,
      "lengthFrames": 14080,
      "peakSeconds": 0.125
    },
    {
      "kind": "vacuum",
      "offsetFrames": 480800,
      "lengthFrames": 43200,
      "peakSeconds": 0.51
    },
    {
      "kind": "vacuum-stop",
      "offsetFrames": 524000,
      "lengthFrames": 16000,
      "peakSeconds": 0.2
    },
    {
      "kind": "big-pop",
      "offsetFrames": 540000,
      "lengthFrames": 3200,
      "peakSeconds": 0.005
    },
    {
      "kind": "big-pop",
      "offsetFrames": 543200,
      "lengthFrames": 3200,
      "peakSeconds": 0.005
    },
    {
      "kind": "big-pop",
      "offsetFrames": 546400,
      "lengthFrames": 3200,
      "peakSeconds": 0.005
    },
    {
      "kind": "big-pop",
      "offsetFrames": 549600,
      "lengthFrames": 3200,
      "peakSeconds": 0.005
    },
    {
      "kind": "big-pop",
      "offsetFrames": 552800,
      "lengthFrames": 3200,
      "peakSeconds": 0.005
    },
    {
      "kind": "big-pop",
      "offsetFrames": 556000,
      "lengthFrames": 3200,
      "peakSeconds": 0.005
    }
  ]
} as const;
