// Generated by tools/audio/prepare-items.py. Frame offsets use the source rate.
export const TOOL_ATLAS = {
  "url": "/audio/item-sounds.wav",
  "sampleRate": 32000,
  "frames": 417120,
  "clips": [
    {
      "kind": "mallet-hit",
      "offsetFrames": 0,
      "lengthFrames": 8000,
      "peakSeconds": 0.01
    },
    {
      "kind": "bat-hit",
      "offsetFrames": 8000,
      "lengthFrames": 7680,
      "peakSeconds": 0.005
    },
    {
      "kind": "ball-hit",
      "offsetFrames": 15680,
      "lengthFrames": 10880,
      "peakSeconds": 0.02
    },
    {
      "kind": "pellet-hit",
      "offsetFrames": 26560,
      "lengthFrames": 2720,
      "peakSeconds": 0.005
    },
    {
      "kind": "mallet-hit",
      "offsetFrames": 29280,
      "lengthFrames": 8000,
      "peakSeconds": 0.01
    },
    {
      "kind": "bat-hit",
      "offsetFrames": 37280,
      "lengthFrames": 7680,
      "peakSeconds": 0.005
    },
    {
      "kind": "ball-hit",
      "offsetFrames": 44960,
      "lengthFrames": 10880,
      "peakSeconds": 0.02
    },
    {
      "kind": "pellet-hit",
      "offsetFrames": 55840,
      "lengthFrames": 2720,
      "peakSeconds": 0.005
    },
    {
      "kind": "mallet-hit",
      "offsetFrames": 58560,
      "lengthFrames": 8000,
      "peakSeconds": 0.01
    },
    {
      "kind": "bat-hit",
      "offsetFrames": 66560,
      "lengthFrames": 7680,
      "peakSeconds": 0.01
    },
    {
      "kind": "ball-hit",
      "offsetFrames": 74240,
      "lengthFrames": 10880,
      "peakSeconds": 0.015
    },
    {
      "kind": "pellet-hit",
      "offsetFrames": 85120,
      "lengthFrames": 2720,
      "peakSeconds": 0.005
    },
    {
      "kind": "parcel-hit",
      "offsetFrames": 87840,
      "lengthFrames": 7680,
      "peakSeconds": 0.01
    },
    {
      "kind": "parcel-hit",
      "offsetFrames": 95520,
      "lengthFrames": 7680,
      "peakSeconds": 0.01
    },
    {
      "kind": "pistol",
      "offsetFrames": 103200,
      "lengthFrames": 8960,
      "peakSeconds": 0.01
    },
    {
      "kind": "pistol",
      "offsetFrames": 112160,
      "lengthFrames": 8960,
      "peakSeconds": 0.01
    },
    {
      "kind": "pistol",
      "offsetFrames": 121120,
      "lengthFrames": 8960,
      "peakSeconds": 0.015
    },
    {
      "kind": "pistol",
      "offsetFrames": 130080,
      "lengthFrames": 8960,
      "peakSeconds": 0.015
    },
    {
      "kind": "launcher",
      "offsetFrames": 139040,
      "lengthFrames": 18560,
      "peakSeconds": 0.06
    },
    {
      "kind": "cannon",
      "offsetFrames": 157600,
      "lengthFrames": 11200,
      "peakSeconds": 0.1
    },
    {
      "kind": "launcher",
      "offsetFrames": 168800,
      "lengthFrames": 18560,
      "peakSeconds": 0.06
    },
    {
      "kind": "cannon",
      "offsetFrames": 187360,
      "lengthFrames": 11200,
      "peakSeconds": 0.1
    },
    {
      "kind": "swish",
      "offsetFrames": 198560,
      "lengthFrames": 6080,
      "peakSeconds": 0.04
    },
    {
      "kind": "heavy-swish",
      "offsetFrames": 204640,
      "lengthFrames": 8000,
      "peakSeconds": 0.065
    },
    {
      "kind": "swish",
      "offsetFrames": 212640,
      "lengthFrames": 6080,
      "peakSeconds": 0.07
    },
    {
      "kind": "heavy-swish",
      "offsetFrames": 218720,
      "lengthFrames": 8000,
      "peakSeconds": 0.1
    },
    {
      "kind": "swish",
      "offsetFrames": 226720,
      "lengthFrames": 6080,
      "peakSeconds": 0.065
    },
    {
      "kind": "heavy-swish",
      "offsetFrames": 232800,
      "lengthFrames": 8000,
      "peakSeconds": 0.1
    },
    {
      "kind": "throw",
      "offsetFrames": 240800,
      "lengthFrames": 5440,
      "peakSeconds": 0.05
    },
    {
      "kind": "throw",
      "offsetFrames": 246240,
      "lengthFrames": 5440,
      "peakSeconds": 0.055
    },
    {
      "kind": "bomb-arm",
      "offsetFrames": 251680,
      "lengthFrames": 5760,
      "peakSeconds": 0.005
    },
    {
      "kind": "bomb-arm",
      "offsetFrames": 257440,
      "lengthFrames": 5760,
      "peakSeconds": 0.005
    },
    {
      "kind": "bomb-blast",
      "offsetFrames": 263200,
      "lengthFrames": 24320,
      "peakSeconds": 0.025
    },
    {
      "kind": "bomb-blast",
      "offsetFrames": 287520,
      "lengthFrames": 24320,
      "peakSeconds": 0.025
    },
    {
      "kind": "rocket-blast",
      "offsetFrames": 311840,
      "lengthFrames": 16000,
      "peakSeconds": 0.02
    },
    {
      "kind": "rocket-blast",
      "offsetFrames": 327840,
      "lengthFrames": 16000,
      "peakSeconds": 0.02
    },
    {
      "kind": "vacuum-start",
      "offsetFrames": 343840,
      "lengthFrames": 14080,
      "peakSeconds": 0.225
    },
    {
      "kind": "vacuum",
      "offsetFrames": 357920,
      "lengthFrames": 43200,
      "peakSeconds": 0.285
    },
    {
      "kind": "vacuum-stop",
      "offsetFrames": 401120,
      "lengthFrames": 16000,
      "peakSeconds": 0.165
    }
  ]
} as const;
